[tool.poetry]
name = "1-bilhao-linhas"
version = "0.1.0"
description = ""
authors = ["Gustavo Dias <gust.weing@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
